FROM golang:1.20-alpine as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN GOOS=linux CGO_ENABLED=0 go build -o smsApp ./cmd

FROM scratch
COPY --from=builder /app/smsApp /app/smsApp
ENTRYPOINT [ "/app/smsApp"]