FROM golang:1.20-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -o authApp ./cmd

FROM scratch
COPY --from=builder /app/authApp /app/authApp
ENTRYPOINT [ "/app/authApp"]