FROM golang:1.20-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -o listenerApp ./cmd

FROM scratch
COPY --from=builder /app/listenerApp /app/listenerApp
ENTRYPOINT [ "/app/listenerApp"]