apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-web
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
      - name: blog-web
        image: "mstgnz/blog-web:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: API_URL
            value: "http://blog-api:8087"
        ports:
          - containerPort: 8088

---

apiVersion: v1
kind: Service
metadata:
  name: blog-web
spec:
  selector:
    app: blog-web
  ports:
    - protocol: TCP
      name: main-port
      port: 8088
      targetPort: 8088