apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
      - name: sms-service
        image: "mstgnz/sms-service:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MAIL_DOMAIN
            value: ""
          - name: MAIL_HOST
            value: "localhost"
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_ENCRYPTION
            value: "none"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: FROM_NAME
            value: "John Smith"
          - name: FROM_ADDRESS
            value: "admin@example.com"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sms-service
spec:
  selector:
    app: sms-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80