FROM golang:1.20-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -o loggerApp ./cmd

FROM scratch
COPY --from=builder /app/loggerApp /app/loggerApp
ENTRYPOINT [ "/app/loggerApp"]